import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Button,
  Heading,
  Flex,
  Text,
  Grid,
  GridItem,
  Input,
  InputGroup,
  InputLeftElement,
  IconButton,
  Badge,
  Stack,
  Divider,
  Avatar,
  AvatarBadge,
  AvatarGroup,
  Box,
  Checkbox,
  VStack,
  HStack,
  Image,
  Spacer,
  Center,
} from "@chakra-ui/react";
import { Menu, MenuButton, MenuList, MenuItem } from "@chakra-ui/react";
import { Search2Icon, DragHandleIcon, HamburgerIcon } from "@chakra-ui/icons";
import { useState } from "react";
import { Sidebar } from "../components/Sidebar";
import { TaskBadge } from "../components/TaskBadge";
import { UserBadge } from "../components/UserBadge";
import { TimeTrackingCollapse } from "@/components/TimeTrackingCollapse";
import { TimeTrackingResume } from "@/components/TimeTrackingResume";
import { TaskDescription } from "@/components/TaskDescription";
import { TaskDescriptionResume } from "@/components/TaskDescriptionResume";
import { SearchFilter } from "@/components/SearchFilter";
import {Stat} from "@/components/Stat";

export default function Home() {
  const [collapse, setCollapse] = useState({ index: null, state: false });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h="100vh" flexDirection="row" overflow="hidden" maxWidth="2000px">
        <Flex
          as="aside"
          w="full"
          h="full"
          maxW={collapse.state ? 350 : 100}
          bg="white"
          alignItems="start"
          flexDirection="column"
          transition="ease-in-out .2s"
        >
          <Sidebar setCollapse={setCollapse} collapse={collapse} />
        </Flex>
        <Flex as="main" w="full" h="full" bg="white">
          {/* Starts second column */}
          <Flex
            w="80%"
            p="2%"
            flexDirection="column"
            overflow="auto"
            minH="100vh"
            backgroundColor="neutrals.light.100"
            position="relative"
          >
           <SearchFilter/>
            <Divider mt={5} />
            <Flex gap={8}>
             
            <Stat symbol="h" concept="Yours & total time" number="03:09" detail="(05:21)" badgeColor="brand.secondary.default"/>
            <Stat symbol="$" concept="Yours & total earnings" number="1,695.00" detail="(4,695.00)" badgeColor="semantic.success.green" />
            <Stat symbol="%" concept="Project progress" number="34%" detail="(34/100)" badgeColor="brand.primary.default"/>

            </Flex>
            <Flex justifyContent="space-between" mt={12} alignItems="center">
              <Heading as="h3" fontWeight="light">
                Tasks list
              </Heading>
              <IconButton
                aria-label="Search database"
                bgColor="brand.primary.default"
                icon={<Search2Icon />}
                rounded="full"
                color="neutrals.light.100"
              />
              <AvatarGroup size="md" max={2}>
                <Avatar
                  name="Ryan Florence"
                  src="https://bit.ly/ryan-florence"
                />
                <Avatar
                  name="Segun Adebayo"
                  src="https://bit.ly/sage-adebayo"
                />
                <Avatar name="Kent Dodds" src="https://bit.ly/kent-c-dodds" />
                <Avatar
                  name="Prosper Otemuyiwa"
                  src="https://bit.ly/prosper-baba"
                />
                <Avatar
                  name="Christian Nwamba"
                  src="https://bit.ly/code-beast"
                />
              </AvatarGroup>
              <Text
                fontWeight="regular"
                color="neutrals.gray.ash"
                fontSize="0.8rem"
              >
                200 elements
              </Text>
              <Divider orientation="vertical" />
              <IconButton
                bg="transparent"
                color="neutrals.gray.steel"
                aria-label="Search database"
                icon={<DragHandleIcon />}
              />
              <IconButton
                variant="outline"
                color="brand.primary.default"
                aria-label="Search database"
                icon={<HamburgerIcon />}
              />
            </Flex>
            <Flex mt={4} flexDirection="column">
              <Box
                p={3}
                my={2}
                border="0.5px"
                borderColor="neutrals.gray.light"
                borderRadius="lg"
                w="100%"
                display="flex"
                alignItems="center"
                boxShadow={"md"}
              >
                <Checkbox
                  variant="circular"
                  size="sm"
                  color="neutrals.gray.navy"
                  w="60%"
                  colorScheme="green"
                  onChange={() => {
                    toggleTodo(todo);
                  }}
                >
                  Request server username & password
                </Checkbox>
                <Flex w="40%" justifyContent="space-around" alignItems="center">
                  <Flex>
                    <Text fontSize="0.8em"> In progress</Text>
                  </Flex>
                  <Flex>
                    <Text
                      fontWeight="bold"
                      fontSize="0.8em"
                      color="neutrals.gray.navy"
                    >
                      {" "}
                      02:54
                    </Text>
                  </Flex>
                  <Flex>
                    <AvatarGroup size="sm" max={2}>
                      <Avatar
                        name="Ryan Florence"
                        src="https://bit.ly/ryan-florence"
                      />
                      <Avatar
                        name="Segun Adebayo"
                        src="https://bit.ly/sage-adebayo"
                      />
                      <Avatar
                        name="Kent Dodds"
                        src="https://bit.ly/kent-c-dodds"
                      />
                      <Avatar
                        name="Prosper Otemuyiwa"
                        src="https://bit.ly/prosper-baba"
                      />
                      <Avatar
                        name="Christian Nwamba"
                        src="https://bit.ly/code-beast"
                      />
                    </AvatarGroup>
                  </Flex>
                  <IconButton
                    variant="outline"
                    color="brand.primary.default"
                    aria-label="Search database"
                    icon={<HamburgerIcon />}
                  />
                </Flex>
              </Box>
              <Box
                p={3}
                my={2}
                border="0.5px"
                borderColor="neutrals.gray.light"
                borderRadius="lg"
                w="100%"
                display="flex"
                alignItems="center"
                boxShadow={"md"}
              >
                <Checkbox
                  variant="circular"
                  size="sm"
                  color="neutrals.gray.navy"
                  w="60%"
                  colorScheme="green"
                  onChange={() => {
                    toggleTodo(todo);
                  }}
                >
                  Request server username & password
                </Checkbox>
                <Flex w="40%" justifyContent="space-around" alignItems="center">
                  <Flex>
                    <Text fontSize="0.8em"> In progress</Text>
                  </Flex>
                  <Flex>
                    <Text
                      fontWeight="bold"
                      fontSize="0.8em"
                      color="neutrals.gray.navy"
                    >
                      {" "}
                      02:54
                    </Text>
                  </Flex>
                  <Flex>
                    <AvatarGroup size="sm" max={2}>
                      <Avatar
                        name="Ryan Florence"
                        src="https://bit.ly/ryan-florence"
                      />
                      <Avatar
                        name="Segun Adebayo"
                        src="https://bit.ly/sage-adebayo"
                      />
                      <Avatar
                        name="Kent Dodds"
                        src="https://bit.ly/kent-c-dodds"
                      />
                      <Avatar
                        name="Prosper Otemuyiwa"
                        src="https://bit.ly/prosper-baba"
                      />
                      <Avatar
                        name="Christian Nwamba"
                        src="https://bit.ly/code-beast"
                      />
                    </AvatarGroup>
                  </Flex>
                  <IconButton
                    variant="outline"
                    color="brand.primary.default"
                    aria-label="Search database"
                    icon={<HamburgerIcon />}
                  />
                </Flex>
              </Box>
              <Box
                p={3}
                my={2}
                border="0.5px"
                borderColor="neutrals.gray.light"
                borderRadius="lg"
                w="100%"
                display="flex"
                alignItems="center"
                boxShadow={"md"}
              >
                <Checkbox
                  variant="circular"
                  size="sm"
                  color="neutrals.gray.navy"
                  w="60%"
                  colorScheme="green"
                  onChange={() => {
                    toggleTodo(todo);
                  }}
                >
                  Request server username & password
                </Checkbox>
                <Flex w="40%" justifyContent="space-around" alignItems="center">
                  <Flex>
                    <Text fontSize="0.8em"> In progress</Text>
                  </Flex>
                  <Flex>
                    <Text
                      fontWeight="bold"
                      fontSize="0.8em"
                      color="neutrals.gray.navy"
                    >
                      {" "}
                      02:54
                    </Text>
                  </Flex>
                  <Flex>
                    <AvatarGroup size="sm" max={2}>
                      <Avatar
                        name="Ryan Florence"
                        src="https://bit.ly/ryan-florence"
                      />
                      <Avatar
                        name="Segun Adebayo"
                        src="https://bit.ly/sage-adebayo"
                      />
                      <Avatar
                        name="Kent Dodds"
                        src="https://bit.ly/kent-c-dodds"
                      />
                      <Avatar
                        name="Prosper Otemuyiwa"
                        src="https://bit.ly/prosper-baba"
                      />
                      <Avatar
                        name="Christian Nwamba"
                        src="https://bit.ly/code-beast"
                      />
                    </AvatarGroup>
                  </Flex>
                  <IconButton
                    variant="outline"
                    color="brand.primary.default"
                    aria-label="Search database"
                    icon={<HamburgerIcon />}
                  />
                </Flex>
              </Box>
            </Flex>
          </Flex>
          <Flex
            w="20%"
            p="1%"
            flexDirection="column"
            overflow="auto"
            minH="100vh"
            bg="neutrals.light.100"
          >
            <Flex justifyContent="space-between">
              <TaskBadge />
              <Center>
                <Divider orientation="vertical" height="20px" />
              </Center>
              <UserBadge
                username="Kolin F."
                role="User"
                showDropdown={true}
                avatarPosition="right"
                avatarSize="sm"
                roleFontWeight="bold"
              />{" "}
            </Flex>
            <TimeTrackingCollapse />
            <HStack mt={0}>
              <TaskDescription />
            </HStack>

            <TaskDescriptionResume />
          </Flex>
        </Flex>
      </Flex>
    </>
  );
}
